[tool.poetry]
name = "aioqzone-feed"
version = "0.9.1a1.dev1"
description = "aioqzone plugin providing higher level api for processing feed."
authors = ["aioqzone <zzzzss990315@gmail.com>"]
license = "AGPL-3.0"
readme = "README.md"
homepage = "https://github.com/aioqzone/aioqzone-feed"
repository = "https://github.com/aioqzone/aioqzone-feed"
documentation = "https://aioqzone.github.io/aioqzone-feed"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/aioqzone/aioqzone-feed/issues"

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
aioqzone = {version = "^0.9.1a1.dev2", allow-prereleases = true}
QzEmoji = { git = "https://github.com/aioqzone/QzEmoji.git", branch = "beta" }
# extras: dev
pre-commit = {version = "^2.17.0", optional = true}
black = {version = "^22.1.0", optional = true}
isort = {version = "^5.10.1", optional = true}
# extras: doc
Sphinx = {version = "^5.0.2", optional = true}
autodoc-pydantic = {version = "^1.6.1", optional = true}
sphinx-autodoc-typehints = {version = "^1.18.3", optional = true}
sphinx-rtd-theme = {version = "^1.0.0", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
pytest-asyncio = "^0.18.2"

[tool.poetry.extras]
dev = [
    "pre-commit",
    "black",
    "isort"
]
doc = [
    "Sphinx",
    "autodoc-pydantic",
    "sphinx-autodoc-typehints",
    "sphinx-rtd-theme"
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


# customize begin
[tool.pytest.ini_options]
pythonpath = 'src'
asyncio_mode = 'strict'
log_cli = 1
log_cli_level = 'WARNING'


[tool.isort]
profile = "black"
line_length = 99

[tool.black]
line-length = 99
target-version = ['py37']
