[tool.poetry]
name = "aioqzone-feed"
version = "0.4.0.dev0"
description = "aioqzone plugin providing higher level api for processing feed."
authors = ["JamzumSum <zzzzss990315@gmail.com>"]
license = "AGPL-3.0"
readme = "README.md"
homepage = "https://github.com/JamzumSum/aioqzone-feed"
repository = "https://github.com/JamzumSum/aioqzone-feed"
# documentation = "https://github.com/JamzumSum/aioqzone-feed/wiki"


[tool.poetry.dependencies]
python = ">=3.7,<3.11"
aioqzone = { git = "https://github.com/JamzumSum/aioqzone.git", branch = "beta" }
QzEmoji = { git = "https://github.com/JamzumSum/QzEmoji.git", branch = "async" }
# extras: dev
tox = {version = "^3.24.5", optional = true}
pre-commit = {version = "^2.17.0", optional = true}
black = {version = "^22.1.0", optional = true}
isort = {version = "^5.10.1", optional = true}
# extras: doc
Sphinx = {version = "^4.4.0", optional = true}
autodoc-pydantic = {version = "^1.6.1", optional = true}
sphinx-autodoc-typehints = {version = "^1.17.0", optional = true}
sphinx-rtd-theme = {version = "^1.0.0", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
pytest-asyncio = "^0.18.2"

[tool.poetry.extras]
dev = [
    "tox",
    "pre-commit",
    "black",
    "isort"
]
doc = [
    "Sphinx",
    "autodoc-pydantic",
    "sphinx-autodoc-typehints",
    "sphinx-rtd-theme"
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


# customize begin
[tool.pytest.ini_options]
pythonpath = 'src'
markers = [
    "needuser: Need user interaction, DO NOT use in ci",
    "incremental: xfail succ cases if pred case failed or skipped",
]
asyncio_mode = 'strict'
log_cli = 1
log_cli_level = 'WARNING'


[tool.isort]
profile = "black"
line_length = 99

[tool.black]
line-length = 99
target-version = ['py37']
