# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Dev CI

on:
  push:
    paths:
      - "src/**"
      - "test/**"
      - ".github/workflows/*"
      - "pyproject.toml"
    branches:
      - dev
      - dev/**

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      pytest_arg: test
    secrets:
      TEST_UIN: ${{ secrets.TEST_UIN }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}

  merge:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: beta
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: ${{ needs.test.outputs.package-version }}
          pr_body: ${{ github.event.head_commit.message }} # only push event has head_commit
