name: Sphinx Build and Deploy

on:
  workflow_dispatch:
  push:
    paths:
      - doc/**
      - ".github/workflows/sphinx.yml"

concurrency:
  group: doc-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sphinx-build-deploy:
    uses: aioqzone/aioqzone/.github/workflows/sphinx.yml@beta
